import type { Metadata } from "next";
import { Teko, Roboto } from "next/font/google";
import "./globals.css";

const teko = Teko({
  variable: "--font-teko",
  subsets: ["latin-ext"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${teko.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
