import type { Metadata } from "next";
import { Teko, Roboto } from "next/font/google";
import "./globals.css";

const teko = Teko({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-teko",
});
const roboto = Roboto({
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${teko.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
